### ISSUE TITLE
How should aggregate queries be handled?

### ISSUE THREAD

**Issue by tarjei** [Versent/redux-crud#14]
Hi, quite often I got an api where I can get a single item using a query like GET /todos/34, where 34 is the id but when I want to fetch a set of items I use something like GET /todos?filter=something&page=2&pageSize=23.

How does redux-crud handle these two cases? Does it handle the paging part in any way wrt to storing state? Also, how should I do a fetch of the data from my store?

This might be on the edges of what redux-crud does today, but I would love to hear if it is something that you think is supported and/or some ideas wrt to how this should be supported.

Tarjei

**Comment by sporto** [comment]
HI @tarjei 

See here a couple of examples on fetching one record or many.

https://github.com/Versent/redux-crud/blob/master/docs/async_action_creators.js#L9-L70

Re paging, all the records will end together in the store. So at the moment it is up to the view to select the correct records from the store that correspond to the current page and limit. E.g using lodash `_.drop` for the page `_.take` for the limit.

**Comment by sporto** [comment]
This seems to be resolved, please re open if you have any other question
