### ISSUE TITLE
Optimistic insertions without client generated key?

### ISSUE THREAD

**Issue by dmt0** [Versent/redux-crud#16]
I really like this lib and I'm thinking of using it as it can save me a lot of redundancy. One thing that stops me now is the whole client-generated-key thing. In my current app, the keys are generated on the backend. I believe this is the right place for generating the keys. I determine whether I should modify a record or create a new one by using PUT and POST respectively. I do not display the keys in the UI at all.

Can a configuration option be added to the lib that would allow the operation without client generated key? I can think of two ways of doing it:
a. don't do optimistic addition
b. do a fetch asynchronously in SUCCESS action and cleanup in FAILURE action to keep the state in sync with the backend.

**Comment by sporto** [comment]
Hi @dmt0 

Optimistic addition (`createStart`) is optional. You can ignore this to avoid dealing with client generated ids. See more here:
https://github.com/Versent/redux-crud#about-optimistic-changes

re `b` this sounds like what `createError` does. But it needs the client generated id to find the record in the collection.

If you know of a more elegant way of handling optimistic creation I would love to know. I tried different things but client generated ids was the only thing that worked well with the flux pattern.

**Comment by dmt0** [comment]
Hi @sporto 

Perhaps when the key is generated on the backend there is simply no elegant way. All I can think of is pulling the whole collection on both SUCCESS and ERROR. On SUCCESS - just to get the ID, on ERROR - to clean up the optimistic insertion. Yes it's ugly and it does create network overhead, and that's why I suggested to make it an option and not the default behaviour.

Actually, in my case, the ID is generated based on a certain rule and on some other data that has to stay on the backend and generating it on the front-end is simply not an option. Hence my enquiry.

**Comment by sporto** [comment]
@dmt0 maybe this is not clear in the readme: the creation of a client generate ids is just temporary, it is just there so it can match the record when it comes back from the server. After the record comes backs this client generated id is thrown away and the server generated id is used instead. So you can have both things: optimistic creation and server generated ids, this is what we have.

I will try to make this clearer

**Comment by dmt0** [comment]
@sporto 
If that's the case, it's all great than. Thanks for the clarification! Do we need that generated ID at all though? You POST an object without ID to the back-end, you get back the response with the generated ID. Match it against one without ID, done.

**Comment by sporto** [comment]
@dmt0 what you are suggesting might work if response times were extremely fast and the user waits for each thing to finish before doing something else. 

But with the async workflow of ajax and flux this is hardly the case, there is a good chance of having more than one new record in transit in a collection, so the generated ids are necessary.
