### ISSUE TITLE
reducer resourceName vs. resourcesName

### ISSUE THREAD

**Issue by scisci** [Versent/redux-crud#2]
It looks like there's an error in the config code for reducers. In reducersFor, its sets the config as resourceName, but then in reducer common.js, it looks for resourcesName and so it comes out undefined. Don't know if it causes an error or not, but looks weird.

**Comment by sporto** [comment]
Right!, this just causes `undefined` to show in the errors, fixing it, thanks.

**Comment by sporto** [comment]
Fixed in https://github.com/Versent/redux-crud/commit/c42f1d143be3e91964a42233cb02bf19fbe4bcc0
