### ISSUE TITLE
Feasible to auto-convert record into immutable ones?

### ISSUE THREAD

**Issue by niksosf** [Versent/redux-crud#24]
Hi there, I am using redux-crud (excellent work!) with seamless immutable and using the stock updateStart() action creator to call the following:

```
axios.patch(
          `/api/v2/invoice/${invoice.id}`,
          { invoice }
        )
        .then(res => dispatch(updateSuccess(res.data)) // line 5
```

But it complains that the record isn't immutable; would it be feasible to have a config option to auto-convert records into immutable ones, so that one doesn't need to add dispatch(updateSuccess(SI(res.data))) for each ajax call?

**Comment by sporto** [comment]
Yes, it will possible to have an option for this. Will keep this issue open as a reminder.

**Comment by sporto** [comment]
This is no longer relevant in v2. We don't use an immutable library anymore in the store. This needs to be done when retrieving the records from the store.
