### ISSUE TITLE
Selecting a single record

### ISSUE THREAD

**Issue by yoursdearboy** [Versent/redux-crud#25]
What is the proper way to select a single record from collection? With Immutable.js I use next code
```js
records.find(r => r.get('id') == id)
```
Don't you think that using map to store collection would be simpler?
```js
records.get(id) // immutable.js
records[id] // plain old js object
```

**Comment by sporto** [comment]
Using maps has the advantage of fast lookup as you say. But you lose the order of records, this was important for us, also operations like filtering records are easier (and probably faster) by using arrays.

So the proper way is using `find` or similar.
