### ISSUE TITLE
Store records by id

### ISSUE THREAD

**Issue by Nauktis** [Versent/redux-crud#29]
Hey,

Very nice library.
It is very handy and avoids a lot of boilerplate code.
But IMHO records should be stored by id rather than in an array.
The current design makes searching records and maintaining sub-lists very inefficient.

Rather than

```
[
   {
      id:1,
      name:"Hello"
   },
   {
      id:2,
      name:"World"
   }
]
```

It would be better to have:

```
{  
   1: {   
      id:1,
      name:"Hello"
   },
   2: {  
      id:2,
      name:"World"
   }
}
```

It still allows to iterate over the collection but also to quickly find one or more particular records.
Have a look at https://github.com/paularmstrong/normalizr

N.

**Comment by sporto** [comment]
Hi, thanks for your input, see some discussion about this here https://github.com/Versent/redux-crud/issues/15 the main reason for having arrays is preserving the order or records as they come from the server

**Comment by mattvague** [comment]
@sporto I also need my store in map-form and I'm currently playing around with creating a wrapper around redux-crud reducers that converts state into an array on the way in and back to a map on the way out and it's crazy simple. Seems to work pretty well, any thoughts on this idea? Would you accept a PR to add a "store as map" setting like this?

**Comment by sporto** [comment]
@mattvague 	thanks for the comment, I'm concerned with the performance of this. Converting from map to array then back to map seems like a lot of overhead. Works but I think it can go against the purpose of using a map, as a map helps to have fast writes into the store.

Let me think about what are the implications of having a baked in map store.

**Comment by mattvague** [comment]
> I'm concerned with the performance of this. Converting from map to array then back to map seems like a lot of overhead

Yeah no, it is not super performant. I started off by forking redux-crud and playing around with doing it the "right way" but it definitely seemed (as you've said elsewhere) non-trivia and I really needed this to work now. The app I'm working on doesn't deal with huge data sets so it seems to be ok but would obviously be great to have it built in.

> Let me think about what are the implications of having a baked in map store.

Cool. Let me know if you can see a reasonable path to making this happen and whether I can help. 

Cheers

**Comment by sporto** [comment]
I have started a branch for this
https://github.com/Versent/redux-crud/pull/38

It will take me a while as I can put very limited time on this. Any help would be appreciated.

**Comment by sporto** [comment]
This is done in v3
