### ISSUE TITLE
How do I import and use action creators?

### ISSUE THREAD

**Issue by hairychris** [Versent/redux-crud#3]
Sorry I am sure I am missing something simple but how do I use these action creators?

    import { actionCreators } from 'actions/devices';
    this.props.dispatch(actionCreators.fetch());

does not seem to work (the file exists and copies your demo users.js with fetch and axios etc).

**Comment by daveslutzkin** [comment]
@sporto will be able to answer in more detail as to the exact intention, but we use them something like this:
```
import reduxCrud from 'redux-crud';
const standardActionCreators = reduxCrud.actionCreatorsFor('model');
...
let actionCreators = {
  fetch() {
    return function(dispatch) {
      const action = standardActionCreators.fetchStart();
      dispatch(action);
      ...
```
Hope that helps.

**Comment by hairychris** [comment]
Thanks for your reply, I still couldn't get it working properly so went back to vanilla Redux, almost certainly my fault and no bug here so I am closing this.

**Comment by sporto** [comment]
hi @hairychris would you be able to paste the code for your `fetch` action creator?

Also do you have the `thunk` middleware? https://github.com/gaearon/redux-thunk this is necessary in order to be able to use async action creators.
