### ISSUE TITLE
Index Action Best Practices

### ISSUE THREAD

**Issue by OAGr** [Versent/redux-crud#4]
I realize that this is called ``redux-crud``, but I was still a bit surprised to realize that there was no way for GETing a list of resources, just to fetch a specific resource.  It took me some time to realize that ``USERS_FETCH_START`` was referring to one specific user.  

I could imagine a few ways to implement collection GET request actions.  What I originally expected was that ``USERS_FETCH_START`` would ``GET`` the ``USERS`` collection, and ``USER_FETCH_START`` would ``GET`` a user resource.  Do you have recommendations about this?

**Comment by sporto** [comment]
Hi @OAGr 	

`USERS_FETCH_START` is meant for just publishing an event that you have started fetching users. 

The action to use when users have been fetched is `USERS_FETCH_SUCCESS`. The action creator takes an array:

```js
fetchSuccess: function(users) {
    return {
      type:    'USERS_FETCH_SUCCESS',
      records: users,
    };
  },
```

So there is no distinction between an individual users and an array. It should always be an array.

We use this like:

```js
const baseActionCreators = reduxCrud.actionCreatorsFor('users')

 fetch() {
    return function(dispatch, getState) {

      const action = baseActionCreators.fetchStart()
      dispatch(action)

      // send the request
      const url = `${host}/users/`
      const promise = axios({
        url: url,
      })

      promise.then(function(response) {
          // dispatch the success action
          const returned = response.data.data
          const successAction = baseActionCreators.fetchSuccess(returned)
          dispatch(successAction)
        }, function(response) {        
          // dispatch the error action
          const errorAction = baseActionCreators.fetchError(response)
          dispatch(errorAction)
        }).catch(function(err) {
          console.error(err.toString())
        })

      return promise
    }
  },
  ```


You can see this example here https://github.com/Versent/react-starter/blob/master/client/src/users/actions.js

I will create a simple example in this repo, will get back to you when this is done, most likely tomorrow.

**Comment by OAGr** [comment]
That makes a lot of sense, thank you.

**Comment by sporto** [comment]
Hi @OAGr in case you are interested I added a basic example app here
https://github.com/Versent/redux-crud/tree/master/example
