### ISSUE TITLE
Where is reduxCrud.Map.reducersFor?

### ISSUE THREAD

**Issue by tslocke** [Versent/redux-crud#40]
In the current latest npm version, `reduxCrud.Map.reducersFor` is `""`

**Comment by sporto** [comment]
Uh, I forgot to link some modules and didn't have a test for that. Sorry. Fixed in 3.0.1

**Comment by tslocke** [comment]
Thanks for the quick fix. 

Nice library. I like how it follows the "redux way" - small set of easy to understand pure functions, very useful.
