### ISSUE TITLE
`createStart` does not mark record as "busy"

### ISSUE THREAD

**Issue by terinjokes** [Versent/redux-crud#5]
Is there a reason `createStart` does not mark records as "busy" like `deleteStart` and `updateStart` do? Right now I have nothing to match against if I want to show these pending records differently in the UI.

**Comment by sporto** [comment]
No good reason, it sounds like a sensible thing to do, will add it.

**Comment by terinjokes** [comment]
In my local fork I've chosen `{pending: true, busy: true}`, but obviously pretty easy to change if you think a better name works better.

**Comment by sporto** [comment]
I published `v0.6.0`. This adds `unsaved` and `busy` to the record on `createStart`. I went for `unsaved` because we are already using this keyword in `updateStart`.

**Comment by terinjokes** [comment]
The downside for using only `unsaved` is that now I can't distingish between "this record has no server component, so don't try to fetch subresources" and "this record exists on the server, perhaps with slightly different state" in my application or UI.

**Comment by sporto** [comment]
hi @terinjokes I don't quite follow, can you explain to me what is the difference between `busy` and `pending` to you? They seem like the same to me.

**Comment by terinjokes** [comment]
@sporto There's a difference.

I display a list of resources that link to another page. Under this list I allow you to add another, and I immediately put it in the list with a label "pending" and I don't allow you to click through to this resource, since that will trigger API calls for a resource that doesn't exist yet.

You can also edit information about the resources (mainly, just the resource name). Since "busy" is set, I can display some UI component that signifies this, but still allow the user to click through (since the API requests that triggers will still succeed).

If createStart overloads "busy" without adding something of it's own, I can't distinguish between these two scenarios. I either have to allow the user to click through (and have a broken app) or always prevent clicking through while a resource is "busy".

**Comment by sporto** [comment]
@terinjokes ok, I understand. So using `unsaved` on both create and update is not good enough. However `pending` doesn't have a good semantic distinction from `busy`. Maybe we can have something like `pending_creation` and 'pending_update`.

**Comment by daveslutzkin** [comment]
@sporto I like that nomenclature.

**Comment by sporto** [comment]
Published 0.7.0, this adds `pendingCreate` and `pendingUpdate`

**Comment by sporto** [comment]
@terinjokes 	Do you think this will do?

**Comment by terinjokes** [comment]
Sorry, I thought I replied previously. This is great, the names describe
what's happening well. Thanks.

-- 
Terin Stock
