### ISSUE TITLE
Initial Map state is an Array

### ISSUE THREAD

**Issue by hwaterke** [Versent/redux-crud#50]
Any reason why the [initial state of the Map reducer](https://github.com/Versent/redux-crud/blob/master/src/reducers/map/reducersFor.ts#L33) is an empty array ([]) and not an empty object ({}) ? I find it confusing.

Please see [#51](https://github.com/Versent/redux-crud/pull/51) for a fix

**Comment by sporto** [comment]
Fixed in PR
