### ISSUE TITLE
Question about _cid

### ISSUE THREAD

**Issue by mkuklis** [Versent/redux-crud#64]
Hey everyone. I'm working on the project where the redux-crud is being used (thank you for creating it). Everything is working well for the most part but we are running into an issue with the `_cid` during update. It looks like the `_cid` attribute is being preserved after successful create:

https://github.com/Versent/redux-crud/blob/master/src/reducers/list/create/success.ts#L25-L29

and it becomes part of the current record. I was wondering if there is any reason for keeping it around after the record was successfully created? I tried to review the source code but I couldn't find any obvious reason. Thanks!

**Comment by sporto** [comment]
Looks like I added this in this commit
https://github.com/Versent/redux-crud/commit/4681fffcd5143cf4bda5cec5b74629be8f745bfd

I can't recall why. Is this causing you problems?

**Comment by mkuklis** [comment]
@sporto the backend we are working with is not allowing us to pass additional fields and it looks like the `_cid` stays around after the record is created. When we try to update it we run into issues. We are currently removing it in `updateAction` but I was curious if that perhaps could be cleanup directly in `redux-crud`.

**Comment by mkuklis** [comment]
@sporto the `_cid` is valuable for optimistic changes during creation but I think it can be cleaned up from the record after it's been successfully created.

**Comment by sporto** [comment]
I think we should remove it. I cannot think of a reason why it should stay. Will do when possible. Or if you would like to open a PR it will be done faster. Thanks.
Removing this would mean a major version if we want to be strict about semver.

**Comment by mkuklis** [comment]
Sounds good! I just created a PR. https://github.com/Versent/redux-crud/pull/65 Thank you!

**Comment by dliroberts** [comment]
Guys, this change just broke my build... definitely should have been a major version! How is my component supposed to track the cid being replaced with the server-provided id?

Here's my current logic. It knows the cid and uses this to find the object once the id has been replaced (using lodash):

`event = _.chain(nextProps.events).values().findLast(event => event._cid == this.props.params.eventId).value();`

What's the appropriate way of doing this after this change? Use setState to store a reference to the object...?

Cheers
Duncan
