### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by xiluo58** [Versent/redux-crud#67]
Thanks for the wonderful work. Is it possible to add a LICENSE file in the root so I can use it in a commercial product?

**Comment by sporto** [comment]
This not enough?
https://github.com/Versent/redux-crud/blob/master/package.json#L34

Do you need a LICENSE.md ?

**Comment by xiluo58** [comment]
I mean a LICENSE file (without md extension)
I see many open source libraries contain this file.

**Comment by sporto** [comment]
Done
