### ISSUE TITLE
Not mapping id to object properly

### ISSUE THREAD

**Issue by dvreed77** [Versent/redux-crud#68]
My API delivers a JSON array that looks something like this

```javascript
[{"id":22, "data": "d"}, {"id": 1, "data": "2"}]
```

I am using the Map Reducer and so I would expect the output to be:

```javascript
{1: {"id": 1}, 22: {"id": 22}}
```

but instead I am getting the following

```javascript
{0: {"id":22}, 1: {"id":1}}
```

Is this correct behavior?

Thank you

**Comment by sporto** [comment]
No, that looks broken. I will investigate this.

**Comment by sporto** [comment]
This seems to be working as expected. At least in the tests
https://github.com/Versent/redux-crud/blob/master/src/reducers/map/fetch/success.test.ts#L27

Any more details you can give me?

Do you pass an additional config to `reducersFor()`. How does it look like?

**Comment by dvreed77** [comment]
Hmm, it must have been my fault, but not sure what is happening. I was trying to do stuff manually in the reducer, and ended up just leaving it like this:

```javascript
const standardReducers = reduxCrud.Map.reducersFor('regexp', {key: 'id'})

function regexpReducers(state={}, action) {
    switch(action.type) {
        case regexpActions.fetchSuccess:
            return merge({}, state, action.records)
        default:
            // pass to the generated reducers
            return standardReducers(state, action);
    }
}
```

Which was causing the issues I spoke about.

Changing it to this:

```javascript
export default combineReducers({
    routing: routerReducer,
    regexp: reduxCrud.Map.reducersFor('regexp')
})
```

works as expected.

Not sure what the difference, but it works. Thanks for the quick reply though!

**Comment by sporto** [comment]
Hi. 

In ` return merge({}, state, action.records)`
`action.records`  should be an array. So it seems that your `merge` is using the indexes.

**Comment by sporto** [comment]
Yes closing, as this isn't a bug.
