### ISSUE TITLE
Config option for immutable vs. mutable store

### ISSUE THREAD

**Issue by mjhm** [Versent/redux-crud#7]
I'm wondering whether the immutable library is central to `redux-crud`.  Would it be difficult to make it an option?  I'm finding that merging immutable data into an existing mutable store is challenging and confusing.  If possible I would rather integrate a mutable version of `redux-crud` first, and then switch the whole store to immutable later.  I might be able to implement a PR if immutability isn't a core requirement of `redux-crud`.

**Comment by sporto** [comment]
Is not core, but recommended, it will just fine with mutable data. Happy to take a PR for this.

**Comment by sporto** [comment]
Done in https://github.com/Versent/redux-crud/pull/9
