### ISSUE TITLE
Optional query parameter for fetch actions

### ISSUE THREAD

**Issue by mjhm** [Versent/redux-crud#8]
The example async fetch action creators in the Redux docs have additional data included in their fetch actions -- specifically the `reddit` parameter in the `requestPosts` and the `receivePosts` in http://rackt.org/redux/docs/advanced/AsyncActions.html#-actions-js

In the spirit of that example, I'm finding that it's important to be able to identify the `fetchStart` actions with their corresponding `fetchSuccess` and `fetchError` actions, so it would be very useful to include an optional (or configurable) `query` parameter on each.

My immediate use case is that I am making two simultaneous requests to the same resource collection `/items`.  One for a single item for a detail view on a dashboard, but another slower request to prefetch all of the remaining items.  I want to display the dashboard results as soon as the first request returns, and enable a selection list when all of the remaining items are returned.  But with the current actions I can't distinguish between these two requests (unless I implement additional actions, which defeats the purpose of the redux-crud).

**Comment by sporto** [comment]
Can you check the `id` or `key` of the items to determine if you have the item you need for rendering? 

We could add an additional `options` payload to the actions, but it seems that there is a simpler solution, which is checking if the item you are interested in is present or not in the state. Thoughts?

**Comment by mjhm** [comment]
Theoretically I can check state for the first item, but I the item list will only show one item until the longer running request completes.  The visual result is a flash of the first item then a rerender of the complete list when the full list is returned. It would be visually better to just not display the list at all until the complete list is returned.

I think what I'm getting at is that the "pending" status of a specific request is potentially important state information, and that more granularity than just the `resourceName` may be needed for some use cases.
Another use case along those lines is throttling the frequency of duplicate long running requests.

**Comment by sporto** [comment]
We are dealing with this by using this library https://github.com/versent/redux-loader, maybe you will find it of interest.

Having said that, what change would you propose that will make your use case easier? Having an `options` payload in all actions will help?

**Comment by mjhm** [comment]
Thanks for the `redux-loader` pointer.  It's nice to see how the `pending` logic is entirely decoupled from the actual fetching logic.

For my use cases just including an `options` payload in the fetch actions will do the trick.  I don't think it's needed by the other actions (except possibly by odd corner cases which can be otherwise handled).

**Comment by sporto** [comment]
Published `0.8.0`. This adds a `data` attribute to the actions payload.
